# Generated by Django 4.0.5 on 2022-06-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalAppD', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ressource',
            new_name='Resource',
        ),
    ]
